name: Java CI with Gradle

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 8
          - 11
          - 17
          - 18
          - 19
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v3.9.0
        with:
          distribution: adopt
          java-version: '${{ matrix.java }}'
      - name: Cache Gradle
        uses: actions/cache@v3.0.11
        with:
          path: ~/.gradle
          key: >-
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: '${{ runner.os }}-gradle-'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build the Jar
        run: './gradlew shadowJar'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: 'Successfully build EternalReports JDK${{ matrix.jdk }}'
          path: build/libs/EternalReports*.jar
